// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkuuwnqiaeguuexeeicw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdXV3bnFpYWVndXVleGVlaWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTMxNDksImV4cCI6MjA2NTUyOTE0OX0.XmS2qgNnnXQ9vhFikDaq2iElUmW-7TG9qyZdlO8R5VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);